### ISSUE TITLE
Responsibilities

### ISSUE THREAD

**Issue by mottosso** [mottosso/docker-maya#1]
### Goal

Centralise where packages and software is installed.
### Problem

Currently, a base image is provided for each Maya distribution. This base image provides basic software, such as `nano` and `git`. Each Maya distribution then provides its own `pip` and then moves on to install Python packages into the native `mayapy`.

The problem with this approach is that Python packages are scattered amongst the 10+ Docker images and that maintenance and updates are made difficult.

Instead, I'd like to install these in the base image. The problem then is that `mayapy` isn't yet available and that we instead need to install onto the native Python distribution of the base image; CentOS 6. Unfortunately, CentOS 6 uses Python 2.6 - which aligns with Maya 2013 - but does not align with Maya 2014+.

I could install to 2.6, and then expose the `site-packages` directory onto the `PYTHONPATH`, effectively making every package available to `mayapy`, but as it would also expose _every other_ native CentOS Python 2.6 package, I ran into trouble, and would expect to run into more trouble. It effectively hides the native 2.7 packages in favour of the older 2.6 packages, such as `os` and `sys`. Probably not a good idea.

Another solution might be to install things by hand, into a dedicated directory such as `/shared/python`, but the problem here is that we can't benefit from `pip` anymore. Or, does `--target` work with `pip` in this circumstance?

**Comment by fredrikaverpil** [comment]
This is just an uneducated thought (I'm new to docker) at 8am in the morning... but could we not install Python 2.7 as part of the docker image side-by-side with Python 2.6 in CentOS 6?

```
./configure --prefix=/opt/python2.7.11 && make && make install
```

When you just execute `pip` 'as-is', it will use pip from Python 2.6. But if you explicitly run `/opt/python2.7.11/bin/pip` you would not need to define the `--target` if your goal is to install packages into the custom Python 2.7 installation.

Do you think that would be useful?

**Comment by mottosso** [comment]
Do you mean installing it in a separate location, and _not_ expose it's binaries to the `PATH` so as to not break other system packages that rely on 2.6?

Sounds like it could work, are you able to give this a go?

**Comment by fredrikaverpil** [comment]
> Do you mean installing it in a separate location, and not expose it's binaries to the PATH so as to not break other system packages that rely on 2.6?

Yep.

> Sounds like it could work, are you able to give this a go?

I'm actually just back from extended parental leave and I haven't used docker before. Just getting into it. Mind giving me a few pointers and I'll be happy to give it a go?

**Comment by mottosso** [comment]
Sure, I'd love to.

Firstly, you'll need to familiarize yourself with Docker. I probably couldn't give you a better introduction than their official tutorials.
- https://training.docker.com/self-paced-training

Next, (or first, depending on your courage) launch the base image and do your magic.

``` bash
$ docker run -ti --rm mottosso/mayabase-centos
```

This will open up a shell within the virtual environment in which you can begin installing Python. Once you're done, we'll push this image (similar to how we push to GitHub) onto the "Docker Hub" where it will automatically start updating all of the `docker-maya` versions with the new base. After a few minutes, we can start opening those up to have a look at whether things are still functional.

``` bash
$ docker run -ti --rm mottosso/maya:2016sp1
$ python
>>> # should say version 2.6
>>> exit()
$ /path/to/python2.7
>>> # should say 2.7
>>> exit()
$ /path/to/python2.7 -m pip install numpy
$ # should compile and install numpy for 2.7
```

**Comment by mottosso** [comment]
Oh btw, the `--rm` flag means that once you `exit` out of the shell, the image will get deleted.

This is great for when you get started and try things out. Whenever you want a clean slate, just say `exit` and then re-run the command. But it also means you can't save any of your work.

When you've found a combination of commands that work, we'll update the ["Dockerfile"](https://github.com/mottosso/mayabase-centos/blob/master/Dockerfile) which is what we'll push to Docker Hub.

On another note, it's been a while since I was engrossed in this and I can't remember what the original issue was.. And what's more, the [GitHub base image](https://github.com/mottosso/mayabase-centos/blob/master/Dockerfile) differs from [the one on Docker Hub](https://hub.docker.com/r/mottosso/mayabase-centos/~/dockerfile/) (see the 2.6 versus 2.7 at the bottom?). So unless you feel like exploring Docker, or to work on it's parent project, [Pyblish CI](https://github.com/pyblish/pyblish-ci), to encounter the original problem, I wouldn't spend too much time on this issue.

**Comment by fredrikaverpil** [comment]
Great, thanks. Will try to have a look at this. Could be a good way of finally getting into docker.

**Comment by monkeez** [comment]
Is using CentOS 7 as a base image a possible solution? It looks like it uses python 2.7 by default instead.

**Comment by mottosso** [comment]
In practice, this hasn't been a problem, and is probably unavoidable anyway. Some packages, like NumPy, are compiled and *must* be installed relative the specific Python distribution shipping with Maya.
