### ISSUE TITLE
"Waiting for Xvfb..." on Mac M1

### ISSUE THREAD

**Issue by JakubKopys** [mottosso/docker-maya#14]
I'm trying to run `docker run -ti --rm mottosso/maya` on my Macbook Pro with an M1 chip, but all I'm getting is "Waiting for Xvfb...".
```
➜  Workspace docker run -ti --platform linux/amd64 --rm mottosso/maya:2022
Unable to find image 'mottosso/maya:2022' locally
2022: Pulling from mottosso/maya
524b0c1e57f8: Pull complete
fdac59c37a2b: Pull complete
5cd912636757: Pull complete
89617c3d5074: Pull complete
0db6b10f3a46: Pull complete
b6f685c74dab: Pull complete
7729487ddc21: Pull complete
1595f5193d01: Pull complete
253509398be5: Pull complete
cad1ff90a08b: Pull complete
200b49b2058a: Pull complete
Digest: sha256:fd76fe0c4382919c337493d1c268b6a42fb6d1169b380685e10d3e559e6a8a1e
Status: Downloaded newer image for mottosso/maya:2022
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
```
I realize this Docker image doesn't provide the arm64 arch version, but I expected it to work since it should use Rosetta by default.

Any idea what could be causing that? It doesn't look like the mayabase-centos7 Dockerfile is on GitHub, so I'm not really able to debug that.

I'm not sure if it makes sense to open this issue there, so feel free to close it. As a side note, I'd appreciate if you could put mayabase-centos7 Dockerfile on github, so I could debug, and possibly try fixing that.

**Comment by mottosso** [comment]
Unclear, try providing your own entrypoint.

```bash
docker run -ti --rm --entrypoint bash mottosso/maya:2022
```

And you can find the original centos7 image here.

- https://registry.hub.docker.com/r/mottosso/mayabase-centos7/tags

You might also have more/different luck with Maya 2024 which is on CentOS 8 (RockyLinux 8).

```bash
docker run -ti --rm mottosso/maya:2024
```

**Comment by JakubKopys** [comment]
Providing the entrypoint didn't change anything, but `docker` run -ti --rm mottosso/maya:2024` works fine, thank you.
