### ISSUE TITLE
Update OS for older Maya versions

### ISSUE THREAD

**Issue by wayne-wu** [mottosso/docker-maya#17]
Looks like CentOS 7 has reached EOL. Would it be possible to update the older Docker files to use a newer Linux OS (looks like 2025 is using RockyLinux)?

Thanks,

**Comment by mottosso** [comment]
It's unclear/unlikely older Maya's even run on newer Linux distributions. But the Dockerfile is included in this repo, swap out e.g. [this](https://github.com/mottosso/docker-maya/blob/2018/Dockerfile#L1) line with any OS and see what happens with `docker build .`. That's also assuming the download link is still valid.

In short, probably not.
