### ISSUE TITLE
Maya 2018 Required

### ISSUE THREAD

**Issue by garveen** [mottosso/docker-maya#5]

**Comment by mottosso** [comment]
Pull requests welcome!

**Comment by monkeez** [comment]
I'm not even sure if there's a download easily available for Linux version of Maya 2018.

**Comment by mottosso** [comment]
The existing versions did take some effort to find as well; Autodesk changes their release pattern for almost every release. If you do find it, post it here and I'll see about getting it included.

**Comment by mottosso** [comment]
Actually, implemented. :)

```bash
$ docker run -ti --rm mottosso/maya:2018
```

**Comment by monkeez** [comment]
That's great, thank you!

Do you mind me asking how you found the Linux release? I spent about an hour earlier today looking for it but could only find Windows and OSX versions on their website.

**Comment by mottosso** [comment]
I just tried a few combinations of the link for 2017, which turned out to be very similar.
