### ISSUE TITLE
Maya 2019 Support

### ISSUE THREAD

**Issue by monkeez** [mottosso/docker-maya#6]
I've spent a few hours trying to find the download link for 2019 myself but I can't seem to find it. Any clues on how to find it?

It'd be great to have 2019 available too.

**Comment by mottosso** [comment]
I've added it, found a link [here](https://linuxhint.com/install_autodesk_maya2019_ubuntu/) and [here](https://forums.autodesk.com/t5/installation-licensing/i-cannot-install-maya-2019/td-p/8771933), but wasn't able to upload it to Docker at the moment; some issues with Docker Hub is preventing the automated build.

You can build it manually for now, by cloning the repo and calling `docker build -t mottosso/maya:2019 .`

**Comment by monkeez** [comment]
Thanks!

Does Docker Hub have issues like this a lot?

**Comment by salanki** [comment]
For some reasons I am getting this when trying to launch Maya2019:
```
/usr/autodesk/maya//bin/maya.bin: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
```

**Comment by salanki** [comment]
Mayabase should be updated to Centos 7.

**Comment by mottosso** [comment]
Yes, that is quite possible, I didn't actually test this version myself. If someone is interested in making this work, please do submit a PR and I'll give Docker Hub another chance too.

**Comment by a772bNsz** [comment]
The link to 2019 in the current Dockerfile is missing a couple of dashes. I pushed the fix on my repo.

**Comment by mottosso** [comment]
Thanks, merged!
