### ISSUE TITLE
Trouble finding prefs folder

### ISSUE THREAD

**Issue by a772bNsz** [mottosso/docker-maya#8]
I get errors saying I'm missing files from maya/2018/prefs folder. How do I get mayapy/docker to see my prefs? maya/2018/prefs is currently at the root beside Dockerfile.

```
pymel.core : INFO : Updating pymel with pre-loaded plugins: renderSetup
pymel.internal.startup : WARNING : Maya startup file /root/maya/2018/prefs/userPrefs.mel does not exist
Warning: file: /usr/autodesk/maya2018/bin/../scripts/startup/initialStartup.mel line 179: Y-axis is already the Up-axis
AbcExport v1.0 using Alembic 1.5.8 (built Dec 24 2015 17:39:02)
AbcImport v1.0 using Alembic 1.5.8 (built Dec 24 2015 17:39:02)
pymel.internal.startup : WARNING : Maya startup file /root/maya/2018/prefs/userNamedCommands.mel does not exist
pymel.internal.startup : WARNING : Maya startup file /root/maya/2018/prefs/pluginPrefs.mel does not exist
```

**Comment by mottosso** [comment]
You'll need to mount your prefs folder into the container. The Docker container is like a separate computer altogether, it doesn't have access to anything but the hardware in yours. Mounting is a way of sharing files between your computer, and the Docker container. Have a look at the Docker docs for how to mount things.
