### ISSUE TITLE
Docker 2018 can't find Arnold

### ISSUE THREAD

**Issue by a772bNsz** [mottosso/docker-maya#9]
When I try to load Arnold `cmds.loadPlugin("mtoa")`, I get this following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/autodesk/maya2018/lib/python2.7/site-packages/pymel/internal/factories.py", line 813, in newUiFunc
    return beforeUiFunc(*args, **kwargs)
  File "/usr/autodesk/maya2018/lib/python2.7/site-packages/pymel/internal/pmcmds.py", line 134, in loadPlugin_wrapped
    res = new_cmd(*new_args, **new_kwargs)
RuntimeError: Plug-in, "mtoa", was not found on MAYA_PLUG_IN_PATH.
```
Looks like I can [fix this](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Maya-EnvVar/files/GUID-8EFB1AC1-ED7D-4099-9EEE-624097872C04-htm.html) with a Maya.env file:
```
#maya.env
MAYA_PLUG_IN_PATH=/Applications/solidangle/mtoa/2018/plug-ins/mtoa.bundle
```
But how do I let docker know where the maya.env is?

**Comment by mottosso** [comment]
Arnold isn't included in [this Maya installer](https://github.com/mottosso/docker-maya/blob/2018/Dockerfile#L7) as far as I know.

To answer your question though, you'll need to mount a folder with a `maya.env` file into the Docker container. Related to #8.

**Comment by orporan** [comment]
@mottosso 
Would you consider adding arnold if I open a PR for it?

**Comment by mottosso** [comment]
I bet you could launch this container, and install Arnold retroactively. Does it need to be in the base image? I suspect most would rather not wait for the added download size.

If you open a PR for it, it would help shine some light on what would be involved. Also try and include download size; if it's neglible then it's probably a good idea.

**Comment by orporan** [comment]
@mottosso 
Yup, I was just assuming if both me and this guy wanted to use arnold it could be beneficial to others. maybe just 2 different docker hub lablels? really up to you.

**Comment by beckylemesmash** [comment]
2024 and I would appreciate having arnold. Currently only

```
bash-4.4$ Render -listRenderers
        turtlebake: TURTLE surface transfer renderer
        sw: Maya software renderer
        file: Use the renderer stored in the Maya file
        hw: Maya hardware renderer
        interBatch: Interactive batch rendering
        vr: Vector renderer
        turtle: TURTLE frame renderer
        default: Use the renderer stored in the Maya file
        hw2: Maya hardware renderer 2
```

**Comment by beckylemesmash** [comment]
"Does it need to be in the base image?"
Yes please sir.

"I suspect most would rather not wait for the added download size."
It's 2024 already and downloads are fast enough already :P

**Comment by beckylemesmash** [comment]
2024 and I would appreciate having arnold. Currently only

```
bash-4.4$ Render -listRenderers
        turtlebake: TURTLE surface transfer renderer
        sw: Maya software renderer
        file: Use the renderer stored in the Maya file
        hw: Maya hardware renderer
        interBatch: Interactive batch rendering
        vr: Vector renderer
        turtle: TURTLE frame renderer
        default: Use the renderer stored in the Maya file
        hw2: Maya hardware renderer 2
```

cc @orporan @mottosso @a772bNsz 

And @mottosso huge cudos for doing so much for community!
